apiVersion: v1
kind: Service
metadata:
 name: grafana-loadbalancer
 namespace: monitoring
 labels:
   app: grafana
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/name: grafana  
  type: LoadBalancer