apiVersion: v1
kind: Service
metadata:
 name: simple-service
 labels:
   app: sample
spec:
  ports:
  - port: 8500
    protocol: TCP
    targetPort: 8500
  selector:
    app: simple-app
  type: LoadBalancer