apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie-app
  name: mealie-app
  namespace: mealie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie-app
  template:
    metadata:
      labels:
        app: mealie-app
    spec:
      containers:
      - image: ghcr.io/mealie-recipes/mealie:v1.3.2
        name: mealie-app
        ports:
        - containerPort: 9000
